# Generated by Django 3.1.5 on 2021-01-15 02:44

import albums.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_add_creation_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('image', models.ImageField(blank=True, null=True, upload_to=albums.models.upload_to)),
                ('album', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='albums.album')),
            ],
        ),
        migrations.AddConstraint(
            model_name='photo',
            constraint=models.UniqueConstraint(fields=('title', 'album'), name='unique_album_title'),
        ),
        migrations.AddConstraint(
            model_name='photo',
            constraint=models.UniqueConstraint(fields=('album', 'image'), name='unique_album_img'),
        ),
    ]
